export const EVENT_CREATED_BIN = 'created_bin'
export const EVENT_UPDATED_BIN = 'updated_bin'
export const EVENT_DELETED_BIN = 'deleted_bin'
export const EVENT_EMPTIED_BIN = 'emptied_bin'
export const EVENT_ADD_REQUEST = 'add_request'
export const EVENT_DELETE_REQUEST = 'delete_request'
export const EVENT_DELETE_ALL_BINS = 'delete_all_bins'